import PDFDocument from "pdfkit";
import type { CompanyConfig } from "./config.js";

function toBuffer(doc: PDFKit.PDFDocument): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];
    doc.on("data", (c) => chunks.push(c as Buffer));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);
  });
}

const money = (n: number) =>
  new Intl.NumberFormat("en-AU", { style: "currency", currency: "AUD" }).format(
    n
  );

function header(doc: PDFKit.PDFDocument, c: CompanyConfig, docTitle: string) {
  doc.fontSize(20).fillColor("#1d4ed8").text(c.companyName, { continued: false });
  doc
    .fontSize(9)
    .fillColor("#475569")
    .text(`ABN ${c.abn}`)
    .text(c.address)
    .text(`${c.email}  ·  ${c.phone}`);
  doc.moveDown();
  doc.fontSize(16).fillColor("#0f172a").text(docTitle);
  doc.moveDown(0.5);
  doc
    .strokeColor("#e2e8f0")
    .moveTo(doc.x, doc.y)
    .lineTo(555, doc.y)
    .stroke();
  doc.moveDown();
}

function lineRow(
  doc: PDFKit.PDFDocument,
  label: string,
  value: string,
  bold = false
) {
  const y = doc.y;
  doc
    .fontSize(10)
    .fillColor("#334155")
    .font(bold ? "Helvetica-Bold" : "Helvetica")
    .text(label, 50, y, { width: 360 })
    .text(value, 410, y, { width: 145, align: "right" });
  doc.moveDown(0.4);
}

export async function generateQuotePdf(
  quote: {
    quoteNumber: string;
    status: string;
    labourHours: number;
    labourRate: number;
    materialCost: number;
    subcontractorCost: number;
    equipmentCost: number;
    travelCost: number;
    disposalCost: number;
    marginPercent: number;
    subtotal: number;
    gst: number;
    total: number;
    validUntil: Date | null;
    notes: string | null;
    account: { name: string };
    workOrder: { workOrderNumber: string; title: string };
  },
  c: CompanyConfig
): Promise<Buffer> {
  const doc = new PDFDocument({ size: "A4", margin: 50 });
  const done = toBuffer(doc);
  header(doc, c, `Quote ${quote.quoteNumber}`);
  doc
    .fontSize(10)
    .fillColor("#334155")
    .text(`Customer: ${quote.account.name}`)
    .text(`Work order: ${quote.workOrder.workOrderNumber} — ${quote.workOrder.title}`)
    .text(`Status: ${quote.status}`)
    .text(
      `Valid until: ${
        quote.validUntil ? new Date(quote.validUntil).toLocaleDateString("en-AU") : "—"
      }`
    );
  doc.moveDown();
  lineRow(
    doc,
    `Labour (${quote.labourHours}h @ ${money(quote.labourRate)})`,
    money(quote.labourHours * quote.labourRate)
  );
  lineRow(doc, "Materials", money(quote.materialCost));
  lineRow(doc, "Subcontractor", money(quote.subcontractorCost));
  lineRow(doc, "Equipment", money(quote.equipmentCost));
  lineRow(doc, "Travel", money(quote.travelCost));
  lineRow(doc, "Disposal", money(quote.disposalCost));
  lineRow(doc, `Margin applied`, `${quote.marginPercent}%`);
  doc.moveDown(0.3);
  lineRow(doc, "Subtotal (ex GST)", money(quote.subtotal), true);
  lineRow(doc, "GST", money(quote.gst));
  lineRow(doc, "Total (inc GST)", money(quote.total), true);
  if (quote.notes) {
    doc.moveDown();
    doc.fontSize(9).fillColor("#64748b").text(quote.notes);
  }
  doc.end();
  return done;
}

export async function generateInvoicePdf(
  invoice: {
    invoiceNumber: string;
    status: string;
    subtotal: number;
    gst: number;
    total: number;
    issuedAt: Date | null;
    dueAt: Date | null;
    notes: string | null;
    account: { name: string };
    workOrder: { workOrderNumber: string } | null;
  },
  c: CompanyConfig
): Promise<Buffer> {
  const doc = new PDFDocument({ size: "A4", margin: 50 });
  const done = toBuffer(doc);
  header(doc, c, `Tax Invoice ${invoice.invoiceNumber}`);
  doc
    .fontSize(10)
    .fillColor("#334155")
    .text(`Bill to: ${invoice.account.name}`)
    .text(`Work order: ${invoice.workOrder?.workOrderNumber ?? "—"}`)
    .text(`Status: ${invoice.status}`)
    .text(
      `Issued: ${
        invoice.issuedAt ? new Date(invoice.issuedAt).toLocaleDateString("en-AU") : "—"
      }`
    )
    .text(
      `Due: ${
        invoice.dueAt ? new Date(invoice.dueAt).toLocaleDateString("en-AU") : "—"
      }`
    );
  doc.moveDown();
  lineRow(doc, "Subtotal (ex GST)", money(invoice.subtotal), true);
  lineRow(doc, "GST", money(invoice.gst));
  lineRow(doc, "Total due (inc GST)", money(invoice.total), true);
  if (invoice.notes) {
    doc.moveDown();
    doc.fontSize(9).fillColor("#64748b").text(invoice.notes);
  }
  doc.moveDown(2);
  doc
    .fontSize(8)
    .fillColor("#94a3b8")
    .text(
      "This document was generated by MaintenanceOS. Operational finance only — not a substitute for your accounting system.",
      { align: "center" }
    );
  doc.end();
  return done;
}
